apiVersion: apps/v1
kind: Deployment
metadata:
  name: galasa-ecosystem-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: galasa-ecosystem-kubernetes-operator
  template:
    metadata:
      labels:
        name: galasa-ecosystem-kubernetes-operator
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      serviceAccountName: galasa-ecosystem-kubernetes-operator
      containers:
        - name: galasa-ecosystem-kubernetes-operator
          image: 192.168.1.115:30466/galasa-ecosystem-kubernetes-operator:0.16.0
          command:
          - galasa-ecosystem-kubernetes-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "galasa-ecosystem-kubernetes-operator"
